#%RAML 1.0
---
title: webServicesAndroid
baseUri: http://192.168.0.29:5051/{version}
version: v1

/usuario:
  /login:
    post:
      description: trae los datos del usuario
      body: 
       application/json:
        type: |
          {
            "type" : "object",
            "required" : true,
            "propiedades": {
              "usuario": {
                "type": "string",
                "required": true
              },
              "password": {
                "type": "string",
                "required": true
          }
        example: |
          {
            "usuario": "elpapurris",
            "password": "unamuysegura321"
          }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "id_usuario": "2",
                    "nombre": "Jacobo",
                    "email": "Jacobo_9410@hotmail.com",
                    "imgURL": "https://image.freepik.com/vector-gratis/perfil-avatar-hombre-icono-redondo_24640-14044.jpg",
                    "token": "sdfgsSDF2SD5FSDFDSFSDFSDFSDFS5DFSDFS.SDF5SDFSD8FSDFSDF.SDFSDFSDFSDF",                    
                  },
                  "success": true,
                  "status": 200
                }
        404:
          body:
            application/json:
              example: |
                {
                  "status": 404,
                  "message": "Usuario no encontrado"
                }
/cursos:
/imagenes:
